// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.9
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({
    effect: "shift",
    prev: "",
    next: "",
    duration: 8 * 100,
    delay: 20 * 100,
    autoPlay: true,
    autoPlayVideo: true,
    playPause: true,
    stopOnHover: false,
    loop: true,
    bullets: 1,
    caption: true,
    captionEffect: "parallax",
    controls: true,
    controlsThumb: false,
    responsive: 1,
    fullScreen: true,
    gestures: 2,
    onBeforeStep: 0,
    images: 0
});